title: "Beat The Loop"
email: beattheloopofficial@gmail.com
timezone: UTC+1
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Darren
paginate: 30
disqus: 'beattheloop'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-MTEJKC7J0F
# name: "Beat The Loop"
# description: "A resource for making the career jump from Finance to Tech."
# url: https://beattheloop.com

# Authors
authors:
  darren:
    name: Darren
    display_name: Darren
    avatar: 'assets/images/sal.png'
    email: beattheloopofficial@gmail.com
    web: ""
    twitter: https://twitter.com/beattheloop
    description: "Author of Beat The Loop, a resource to help you make the career jump from Finance To Tech."
  john:
    name: John
    display_name: John
    avatar: 'assets/images/john.png'
    email: ""
    web: ""
    twitter: ""
    description: "This is the author box. Write a short description of the author here. TEST."

# Social
social:
  instagram: https://www.instagram.com/beattheloop
  linked_in: https://www.linkedin.com/
  twitter: https://twitter.com/beattheloop

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives